### ISSUE TITLE
Open Opps terms and conditions.

### ISSUE THREAD

**Issue by yraza261** [USAJOBS/team-titan#1090] opened 2018-09-12 18:45 UTC
- Get Open Opps approved by Victor
- Get correct URL to terms and conditions

**Comment by humancompanion** [comment] 2018-09-17 13:30
@dalenard21 and @Piglady64 to gather the content. Create a Word doc and hand it to Brice and co. We don't feel comfortable posting this to github as it isn't a .gov domain.

**Comment by dalenard21** [comment] 2018-09-20 14:56
Can we move this to the Open Opps board?

**Comment by humancompanion** [comment] 2018-09-21 13:31
This is a duplicate of https://github.com/openopps/OpenOppsTasks/issues/105

**Closed by humancompanion** 2018-09-21 13:31 UTC
Labels: Content, duplicate
